name: SlimefunOreChunks
version: ${project.version}
author: TheBusyBiscuit
description: Дополнение к Slimefun, которое добавляет различные пыли для геодобытчика
website: https://github.com/TheBusyBiscuit/SlimefunOreChunks

main: io.github.thebusybiscuit.slimefunorechunks.OreChunks
depend: [Slimefun]

api-version: 1.14